export type Locale = "en" | "es";

// ── Team ─────────────────────────────────────────────────────────────────────

export const TEAM_MEMBERS = [
  // ── Core team ────────────────────────────────────────────────────────────────
  {
    group: "core" as const,
    name: "Dario Missael Rocha-Castellanos",
    flag: "🇲🇽",
    role_en: "Project Lead · Platform Development",
    role_es: "Líder del proyecto · Desarrollo de plataforma",
    institution: "Program in Global Surgery and Social Change, Harvard Medical School",
    bio_en: "Physician from Mexico and current researcher at the Program in Global Surgery and Social Change, Harvard Medical School. Leads the development of Open Trauma Registry and its adaptation for hospital use.",
    bio_es: "Médico mexicano e investigador en el Programa de Cirugía Global y Cambio Social de Harvard Medical School. Lidera el desarrollo de Open Trauma Registry y su adaptación para uso hospitalario.",
    initials: "DR",
    color: "bg-red-600",
    photo: "/team/dario-rocha.jpg",
  },
  // ── Research team ────────────────────────────────────────────────────────────
  {
    group: "research" as const,
    name: "Nardeen B. Dawood, MD",
    flag: "🇺🇸",
    role_en: "Research Fellow · Research Team",
    role_es: "Investigadora · Equipo de investigación",
    institution: "NYU Langone · Program in Global Surgery and Social Change, Harvard Medical School",
    bio_en: "Surgery resident at NYU Langone and research fellow at the Program in Global Surgery and Social Change. Supports research activities related to trauma registry implementation.",
    bio_es: "Residente de cirugía en NYU Langone e investigadora en el Programa de Cirugía Global y Cambio Social. Apoya las actividades de investigación relacionadas con la implementación del registro de trauma.",
    initials: "ND",
    color: "bg-blue-600",
    photo: "/team/nardeen-dawood.jpg",
  },
  {
    group: "research" as const,
    name: "Amelia Levi, MD",
    flag: "🇺🇸",
    role_en: "Research Collaborator · Surgery and Trauma",
    role_es: "Colaboradora de investigación · Cirugía y trauma",
    institution: "RESPOND collaboration team",
    bio_en: "Surgery resident and researcher collaborating on RESPOND-related trauma and implementation work.",
    bio_es: "Residente de cirugía e investigadora que colabora en actividades de trauma e implementación relacionadas con RESPOND.",
    initials: "AL",
    color: "bg-emerald-600",
    photo: "/team/amelia-levi.jpg",
  },
  // ── Faculty advisors ─────────────────────────────────────────────────────────
  {
    group: "advisors" as const,
    name: "Nakul Raykar, MD, MPH",
    flag: "🇺🇸",
    role_en: "Faculty Mentor · Trauma Systems",
    role_es: "Mentor académico · Sistemas de trauma",
    institution: "Harvard Medical School · Brigham and Women's Hospital",
    bio_en: "Trauma surgeon at Brigham and Women's Hospital and Fellowship Director of the Program in Global Surgery and Social Change. Advises on trauma systems, implementation science, and registry strategy.",
    bio_es: "Cirujano de trauma en Brigham and Women's Hospital y Director del Fellowship del Programa de Cirugía Global y Cambio Social. Asesora en sistemas de trauma, ciencia de implementación y estrategia del registro.",
    initials: "NR",
    color: "bg-teal-600",
    photo: "/team/nakul-raykar.webp",
  },
  {
    group: "advisors" as const,
    name: "John G. Meara, MD, DMD, MBA",
    flag: "🇺🇸",
    role_en: "Senior Advisor · Global Surgery",
    role_es: "Asesor principal · Cirugía global",
    institution: "Boston Children's Hospital · Harvard Medical School",
    bio_en: "Plastic Surgeon-in-Chief at Boston Children's Hospital and Professor of Surgery at Harvard Medical School. Provides senior guidance on global surgery and surgical system strengthening.",
    bio_es: "Jefe de Cirugía Plástica en Boston Children's Hospital y Profesor de Cirugía en Harvard Medical School. Brinda orientación en cirugía global y fortalecimiento de sistemas quirúrgicos.",
    initials: "JM",
    color: "bg-slate-700",
    photo: "/team/john-meara.webp",
  },
  {
    group: "advisors" as const,
    name: "Juan Carlos Puyana, MD, FRCSC, FACS, FACCP",
    flag: "🇮🇪",
    role_en: "Trauma Surgery Advisor",
    role_es: "Asesor en cirugía de trauma",
    institution: "RCSI University of Medicine and Health Sciences · University of Pittsburgh",
    bio_en: "O'Brien Chair of Global Surgery at RCSI and Professor of Trauma Surgery at the University of Pittsburgh. Advises on trauma systems and registry implementation.",
    bio_es: "Titular de la Cátedra O'Brien de Cirugía Global en RCSI y Profesor de Cirugía de Trauma en la Universidad de Pittsburgh. Asesora en sistemas de trauma e implementación del registro.",
    initials: "JP",
    color: "bg-orange-600",
    photo: "/team/juan-carlos-puyana.jpg",
  },
  // ── Guatemala Implementation Team ────────────────────────────────────────────
  {
    group: "guatemala" as const,
    name: "Sabrina Marie Asturias Simons, MD",
    flag: "🇬🇹",
    role_en: "Guatemala Implementation Lead",
    role_es: "Líder de implementación en Guatemala",
    institution: "Hospital Roosevelt, Guatemala",
    bio_en: "Chief of Trauma and Emergency Surgery at Hospital Roosevelt and NIH-funded trauma systems investigator. Leads local implementation and clinical coordination in Guatemala.",
    bio_es: "Jefa de Cirugía de Trauma y Emergencias en Hospital Roosevelt e investigadora financiada por el NIH en sistemas de trauma. Lidera la implementación local y la coordinación clínica en Guatemala.",
    initials: "SA",
    color: "bg-rose-600",
    photo: "/team/sabrina-asturias.png",
  },
  {
    group: "guatemala" as const,
    name: "Jose Carlos Monzon",
    flag: "🇬🇹",
    role_en: "Implementation Collaborator",
    role_es: "Colaborador de implementación",
    institution: "Hospital Roosevelt, Guatemala",
    bio_en: "Supports local implementation, workflow adaptation, and data quality processes at Hospital Roosevelt.",
    bio_es: "Apoya la implementación local, la adaptación de flujos de trabajo y los procesos de calidad de datos en Hospital Roosevelt.",
    initials: "JM",
    color: "bg-amber-600",
    photo: "/team/jose-monzon.png",
  },
  {
    group: "guatemala" as const,
    name: "Carlos Terraza",
    flag: "🇬🇹",
    role_en: "Implementation Collaborator",
    role_es: "Colaborador de implementación",
    institution: "Hospital Roosevelt, Guatemala",
    bio_en: "Supports local implementation planning, registry adaptation, and coordination with clinical teams.",
    bio_es: "Apoya la planificación de implementación local, la adaptación del registro y la coordinación con los equipos clínicos.",
    initials: "CT",
    color: "bg-violet-600",
    photo: "/team/carlos-terraza.webp",
  },
];

export const PARTNERS = [
  { name: "RESPOND Guatemala", abbr: "RESPOND" },
  { name: "Hospital Roosevelt", abbr: "HR" },
  { name: "Harvard Program in Global Surgery and Social Change", abbr: "PGSSC" },
  { name: "Brigham and Women's Hospital", abbr: "BWH" },
  { name: "Boston Children's Hospital", abbr: "BCH" },
];

// ── Copy ─────────────────────────────────────────────────────────────────────

const en = {
  nav: {
    brand: "Open Trauma Registry",
    links: [
      { label: "About", href: "#about" },
      { label: "Platform", href: "#platform" },
      { label: "Guatemala", href: "#guatemala" },
      { label: "Evidence", href: "#evidence" },
      { label: "Team", href: "#team" },
      { label: "Demo", href: "#demo" },
      { label: "Import Engine", href: "#import-engine" },
      { label: "Contact", href: "#contact" },
    ],
    cta_demo: "Try the demo",
    cta_register: "Request a pilot",
    lang_toggle: "ES",
  },
  hero: {
    badge: "First implementation: Hospital Roosevelt, Guatemala",
    label: "Open-source · Free · Works offline",
    headline: "An open trauma registry built for hospitals that need usable data.",
    subheadline:
      "OpenTrauma Registry helps hospitals collect, review, and export trauma data without adding unnecessary complexity to daily clinical work.",
    cta_demo: "Try the demo",
    cta_register: "Request a pilot",
    stats: ["Free and open-source", "Works offline", "Spanish and English", "Export-ready data"],
  },
  context: {
    tag: "Why This Matters",
    title: "Trauma care improves when hospitals can see and use their data.",
    body1: "Hospitals care for injured patients every day, but many still lack a practical way to see who is being injured, what treatment they receive, where delays occur, and what outcomes follow.",
    body2: "Without reliable trauma data, delays stay hidden, outcomes are harder to review, and improvement efforts depend on incomplete information.",
    supporting_line: "Data captured at the bedside becomes the evidence base for better care.",
    flow: [
      { num: "01", title: "Capture cases", desc: "Who was injured, where, and how", icon: "Activity" },
      { num: "02", title: "Record care", desc: "Vitals, injuries, procedures, and key times", icon: "ListChecks" },
      { num: "03", title: "Review outcomes", desc: "Deaths, delays, complications, missing data", icon: "BarChart2" },
      { num: "04", title: "Improve systems", desc: "Audits, reports, planning, and research", icon: "TrendingUp" },
    ],
  },
  problem: {
    tag: "The Sustainability Gap",
    title: "Many trauma registries start with strong clinical value, but are difficult to sustain when the tools do not fit hospital work.",
    body: "The challenge is not only starting a registry, but keeping it useful for the people entering and reviewing the data.",
    cards: [
      {
        icon: "AlertTriangle",
        title: "Tools too complex for busy clinical teams",
        desc: "Many registries are built like research databases. Long forms and rigid fields make data entry harder for teams that are already stretched.",
        blockers: [],
      },
      {
        icon: "AlertTriangle",
        title: "Technical requirements are hard to sustain",
        desc: "Some platforms depend on stable internet, IT support, paid licenses, or ongoing maintenance that public hospitals with limited infrastructure cannot guarantee.",
        blockers: ["Internet required", "IT support", "Paid license", "Server maintenance"],
      },
      {
        icon: "AlertTriangle",
        title: "Data collected, but rarely used",
        desc: "When registry data is disconnected from review meetings and reporting tools, teams have little reason to keep entering it. The registry becomes an archive instead of a tool for improvement.",
        blockers: [],
      },
    ],
    closing: "That is why OpenTrauma Registry was built differently.",
  },
  our_solution: {
    tag: "Our Solution",
    title: "A practical trauma registry for everyday hospital work.",
    body: "OpenTrauma Registry is a free, open-source platform designed to fit the way hospital teams already work.",
    features: [
      "Works with or without internet",
      "Usable on phones and computers",
      "Spanish and English",
      "Automatic trauma score calculation",
      "Export-ready datasets",
      "Configurable for each center",
    ],
    workflow: [
      { step: "Set up", desc: "Configure your center, users, and selected fields." },
      { step: "Collect", desc: "Enter trauma cases online or offline." },
      { step: "Review", desc: "Check completeness, summaries, and exports." },
    ],
    cards: [
      { icon: "Activity", title: "Capture", desc: "Record standardized trauma cases." },
      { icon: "BarChart2", title: "Review", desc: "Track completeness, scores, and outcomes." },
      { icon: "TrendingUp", title: "Improve", desc: "Export data for audit, reporting, and research." },
    ],
  },
  solution: {
    tag: "The Platform",
    title: "Built for trauma teams that need usable data, not another complicated system.",
    body: "The platform brings case entry, score calculation, data quality checks, summary views, and exports into a single registry process.",
    features: [
      {
        icon: "Wifi",
        title: "Offline use",
        desc: "Records are saved locally and synced when internet access returns.",
      },
      {
        icon: "ListChecks",
        title: "Step-by-step case entry",
        desc: "A structured form guides users from injury mechanism to hospital outcomes.",
      },
      {
        icon: "Calculator",
        title: "Automatic score calculation",
        desc: "GCS, Shock Index, and ISS can be calculated from entered variables.",
      },
      {
        icon: "BarChart2",
        title: "Data quality checks",
        desc: "Completeness indicators help teams see what is missing before review or export.",
      },
      {
        icon: "Settings2",
        title: "Local configuration",
        desc: "Hospitals can adjust selected fields and local options.",
      },
      {
        icon: "Download",
        title: "Exports",
        desc: "Download clean datasets for audit, reporting, or research.",
      },
    ],
  },
  platform: {
    tag: "Use Cases",
    title: "Use cases",
    cards: [
      {
        icon: "Building2",
        title: "Single-hospital registry",
        desc: "For hospitals starting or rebuilding trauma data collection.",
      },
      {
        icon: "Network",
        title: "Multicenter collaboration",
        desc: "A shared dataset for hospitals working together across sites.",
      },
      {
        icon: "TrendingUp",
        title: "QI and reporting",
        desc: "Track missing data, review outcomes, and prepare reports for clinical meetings.",
      },
      {
        icon: "Globe",
        title: "Clinical research",
        desc: "Export structured data for approved research projects.",
      },
      {
        icon: "AlertTriangle",
        title: "Mass casualty events",
        desc: "Simplified case entry during high-volume events.",
      },
      {
        icon: "Layers",
        title: "Future modules",
        desc: "The same structure could later support other acute care or surgical registries.",
      },
    ],
  },
  guatemala: {
    tag: "First Implementation",
    title: "Developed from lessons learned at Hospital Roosevelt, Guatemala.",
    body: "OpenTrauma Registry was developed after a prior trauma registry at Hospital Roosevelt was discontinued. The redesign was shaped by feedback from registrars, clinicians, and local implementation partners, with a focus on usability, offline use, simplified forms, and data that teams could actually use.",
    timeline: [
      { year: "2019–2021", event: "REDCap-based trauma registry implemented at Hospital Roosevelt." },
      { year: "2021", event: "Registry discontinued." },
      { year: "2024–2025", event: "Registry evaluation and feedback from registrars and clinical staff reviewed." },
      { year: "2025–2026", event: "Open Trauma Registry platform developed." },
      { year: "2026", event: "Ready for demonstration and external implementation." },
    ],
  },
  evidence: {
    tag: "Evidence",
    title: "Evidence behind the redesign.",
    subtitle: "The platform responds to barriers identified during evaluation of the prior registry, including incomplete variables, workflow burden, and limited use of collected data.",
    abstract_title: "When Trauma Registries Fail: Low-Cost, Stakeholder-Informed Redesign of a Trauma Registry in Guatemala",
    event: "38th Pan-American Congress of Trauma · PTS 2026 · Cartagena, Colombia",
    findings: [
      "775 patients enrolled before the registry was discontinued",
      "Key barriers: connectivity, data-entry time, interface complexity, mobile incompatibility, and registrar workload",
      "Variables most relevant for clinical review were often less complete",
      "These findings directly shaped the current platform design",
    ],
    cta: "Read abstract",
  },
  team: {
    tag: "Team",
    title: "Project team and implementation partners.",
    subtitle: "Collaborators in trauma surgery, global surgery, emergency medicine, implementation science, and clinical data systems.",
    research_title: "Research Team",
    advisors_title: "Faculty Advisors",
    guatemala_title: "Guatemala Implementation Team",
  },
  partners: {
    tag: "Partners",
    title: "Partners and implementation network.",
    subtitle: "Clinical and academic partners supporting trauma care, data systems, and future implementation.",
    future: "Interested in joining as an implementation partner?",
    future_cta: "Contact us",
  },
  implementation: {
    tag: "How We Support Implementation",
    title: "How we can work with your hospital.",
    body: "We can help your hospital define registry goals, configure the platform, train users, and plan exports for QI, reporting, or research.",
    cards: [
      {
        icon: "Building2",
        title: "Set up your center",
        desc: "Create users, roles, and center-specific settings.",
      },
      {
        icon: "Settings2",
        title: "Adapt the registry",
        desc: "Select fields and local options that fit your context.",
      },
      {
        icon: "Users",
        title: "Train your team",
        desc: "Support registrars and clinical staff during early use.",
      },
      {
        icon: "BarChart2",
        title: "Turn data into reports",
        desc: "Use exports and summaries for audit, research, and hospital planning.",
      },
    ],
    cta: "Request a pilot",
  },
  demo: {
    tag: "Demo",
    title: "Try the demo.",
    subtitle: "Explore a sample trauma registry workflow with pre-loaded cases and no patient data.",
    note: "Sample trauma cases are pre-loaded. Explore completeness checks, score calculation, and data export.",
    cards: [
      {
        flag: "🇬🇹",
        label: "Demo · Guatemala Center",
        recommended: false,
        email: "test@respond.gt",
        pass: "testpassword123",
        note: "Pre-loaded test data for the Guatemala implementation environment.",
      },
      {
        flag: "🌎",
        label: "Demo · Sample registry",
        recommended: true,
        email: "demo@respondtraumaregistry.com",
        pass: "RESPOND2026!",
        note: "Sample trauma cases for completeness review and export.",
      },
    ],
    email_label: "Email",
    pass_label: "Password",
    login_cta: "Try the demo",
  },
  contact: {
    tag: "Implementation Request",
    title: "Request a pilot.",
    subtitle:
      "Tell us about your hospital or trauma program, and we will follow up about demo access, pilot setup, or collaboration.",
    fields: {
      name: "Full name",
      email: "Email",
      institution: "Institution or hospital",
      country: "Country",
      role: "Your role",
      center_type: "Type of center",
      volume: "Estimated monthly trauma volume",
      interest: "Primary interest",
      message: "Message",
    },
    roles: ["Trauma surgeon", "Emergency physician", "Nurse", "Researcher", "Registrar / data manager", "Hospital administrator", "Other"],
    center_types: ["Public hospital", "Private hospital", "Academic medical center", "Community hospital", "Humanitarian or conflict setting", "Research institution", "Other"],
    interests: [
      "Try the demo",
      "Request a pilot",
      "Single-center implementation",
      "Multicenter collaboration",
      "Research partnership",
      "Technical questions",
    ],
    submit: "Submit request",
    success_title: "Request received.",
    success_body: "We will follow up within 2–3 business days.",
  },
  footer: {
    description:
      "A free, open-source platform to help hospitals collect and use trauma data. First implementation: Hospital Roosevelt, Guatemala.",
    links: [
      { label: "About", href: "#about" },
      { label: "Platform", href: "#platform" },
      { label: "Evidence", href: "#evidence" },
      { label: "Demo", href: "#demo" },
      { label: "Request a pilot", href: "#contact" },
      { label: "GitHub", href: "https://github.com" },
      { label: "Contact", href: "#contact" },
    ],
    copyright: "Open Trauma Registry · Open source · Free for trauma centers",
  },
};

const es: typeof en = {
  nav: {
    brand: "Open Trauma Registry",
    links: [
      { label: "Por qué importa", href: "#about" },
      { label: "Plataforma", href: "#platform" },
      { label: "Guatemala", href: "#guatemala" },
      { label: "Evidencia", href: "#evidence" },
      { label: "Equipo", href: "#team" },
      { label: "Demo", href: "#demo" },
      { label: "Motor de importación", href: "#import-engine" },
      { label: "Contacto", href: "#contact" },
    ],
    cta_demo: "Probar la demo",
    cta_register: "Solicitar piloto",
    lang_toggle: "EN",
  },
  hero: {
    badge: "Primera implementación: Hospital Roosevelt, Guatemala",
    label: "Código abierto · Gratuito · Funciona sin internet",
    headline: "Un registro de trauma abierto, práctico y fácil de implementar.",
    subheadline:
      "OpenTrauma Registry ayuda a los hospitales a capturar datos de trauma, monitorear la calidad de la información, calcular scores clínicos y exportar datos listos para auditoría, investigación y mejora de calidad.",
    cta_demo: "Probar la demo",
    cta_register: "Solicitar piloto",
    stats: ["Gratuito", "Funciona sin internet", "Español / Inglés", "Exportación CSV / Excel"],
  },
  context: {
    tag: "Por qué importa",
    title: "La atención del trauma mejora cuando los hospitales pueden usar sus datos.",
    body1: "Los hospitales atienden pacientes con trauma todos los días, pero muchos aún no cuentan con una forma práctica de registrar quiénes son, qué atención reciben, dónde ocurren los retrasos y cuáles son sus desenlaces.",
    body2: "Sin datos útiles, los retrasos permanecen invisibles y la mejora de calidad depende de suposiciones.",
    supporting_line: "Los datos del pie de cama son la base de evidencia para mejorar la atención.",
    flow: [
      { num: "01", title: "Capturar casos", desc: "¿Quién se lesionó, dónde y cómo?", icon: "Activity" },
      { num: "02", title: "Registrar la atención", desc: "Signos vitales, lesiones, procedimientos y tiempos clave.", icon: "ListChecks" },
      { num: "03", title: "Revisar desenlaces", desc: "Muertes, retrasos, complicaciones y datos faltantes.", icon: "BarChart2" },
      { num: "04", title: "Mejorar el sistema", desc: "Paneles de control, auditoría, planeación e investigación.", icon: "TrendingUp" },
    ],
  },
  problem: {
    tag: "La brecha de sostenibilidad",
    title: "Muchos registros de trauma comienzan con fuerza, pero se vuelven difíciles de sostener cuando las herramientas no se adaptan al trabajo diario del hospital.",
    body: "El desafío no es solo iniciar un registro, sino mantenerlo útil, accesible y conectado con decisiones clínicas reales.",
    cards: [
      {
        icon: "AlertTriangle",
        title: "Herramientas demasiado complejas",
        desc: "Formularios largos y campos rígidos dificultan mantener la captura de datos durante la atención clínica.",
        blockers: [],
      },
      {
        icon: "AlertTriangle",
        title: "Requisitos técnicos difíciles de sostener",
        desc: "Muchas plataformas dependen de internet estable, soporte técnico, licencias pagadas o mantenimiento especializado.",
        blockers: ["Internet estable", "Soporte técnico", "Licencia pagada", "Mantenimiento especializado"],
      },
      {
        icon: "AlertTriangle",
        title: "Datos recopilados, pero poco utilizados",
        desc: "Cuando los datos no se conectan con paneles de control y decisiones clínicas, el registro se vuelve un archivo en lugar de una herramienta de mejora.",
        blockers: [],
      },
    ],
    closing: "Por eso OpenTrauma Registry fue diseñado de otra manera.",
  },
  our_solution: {
    tag: "Nuestra solución",
    title: "Un registro de trauma práctico para el trabajo diario del hospital.",
    body: "OpenTrauma Registry es una plataforma gratuita y de código abierto para capturar datos hospitalarios de trauma, diseñada para integrarse al trabajo diario de los equipos clínicos.",
    features: [
      "Funciona aunque no haya internet",
      "Se puede usar en teléfonos y computadoras",
      "Disponible en español e inglés",
      "Calcula scores de trauma automáticamente",
      "Incluye paneles de control y datos exportables",
      "Configurable para cada centro",
    ],
    workflow: [
      { step: "Iniciar", desc: "Configura tu centro, crea usuarios y ajusta los campos." },
      { step: "Capturar", desc: "Registra casos de trauma aunque no haya conexión a internet." },
      { step: "Usar", desc: "Revisa paneles de control, exporta datos y mejora la calidad." },
    ],
    cards: [
      { icon: "Activity", title: "Capturar", desc: "Registrar casos estandarizados de trauma." },
      { icon: "BarChart2", title: "Revisar", desc: "Monitorear completitud, scores y desenlaces." },
      { icon: "TrendingUp", title: "Mejorar", desc: "Usar paneles de control y exportaciones para la toma de decisiones." },
    ],
  },
  solution: {
    tag: "La plataforma",
    title: "Diseñada para capturar datos de trauma en la práctica diaria.",
    body: "OpenTrauma Registry combina formularios simples, funcionamiento con o sin internet, cálculo automático de scores, paneles de calidad de datos y exportaciones listas para análisis.",
    features: [
      {
        icon: "Wifi",
        title: "Funciona aunque no haya internet",
        desc: "Los registros se guardan en el dispositivo y se sincronizan automáticamente cuando se restablece la conexión.",
      },
      {
        icon: "ListChecks",
        title: "Flujo estructurado de captura",
        desc: "Ingreso de casos por pasos: mecanismo, signos vitales, lesiones, procedimientos, desenlaces y seguimiento.",
      },
      {
        icon: "Calculator",
        title: "Cálculo automático de scores",
        desc: "GCS, Índice de choque, ISS, RTS, TRISS y probabilidad de supervivencia se calculan de forma automática.",
      },
      {
        icon: "BarChart2",
        title: "Panel de calidad de datos",
        desc: "Los indicadores de completitud muestran qué campos tienen información faltante.",
      },
      {
        icon: "Settings2",
        title: "Configurable para cada centro",
        desc: "Los campos y opciones locales se pueden ajustar según las necesidades de cada hospital.",
      },
      {
        icon: "Download",
        title: "Exportación de datos",
        desc: "Exportación a CSV y Excel para auditoría, informes e investigación.",
      },
    ],
  },
  platform: {
    tag: "Casos de uso",
    title: "Casos de uso",
    cards: [
      {
        icon: "Building2",
        title: "Registro en un solo hospital",
        desc: "Registro de trauma independiente para un hospital.",
      },
      {
        icon: "Network",
        title: "Colaboración multicéntrica",
        desc: "Estructura de datos compartida entre centros participantes.",
      },
      {
        icon: "TrendingUp",
        title: "Mejora de calidad",
        desc: "Seguimiento de completitud, revisión de desenlaces e informes periódicos.",
      },
      {
        icon: "Globe",
        title: "Vigilancia epidemiológica",
        desc: "Exportación estandarizada para análisis regional o nacional.",
      },
      {
        icon: "AlertTriangle",
        title: "Incidentes con múltiples víctimas",
        desc: "Captura simplificada para eventos de alto volumen.",
      },
      {
        icon: "Layers",
        title: "Módulos futuros",
        desc: "La plataforma puede adaptarse para otros registros de atención aguda o cirugía de emergencia.",
      },
    ],
  },
  guatemala: {
    tag: "Primera implementación",
    title: "Desarrollado a partir de la experiencia en Hospital Roosevelt, Guatemala.",
    body: "El rediseño se basó en retroalimentación de registradores, personal clínico y actores clave, con énfasis en facilidad de uso, funcionamiento con o sin internet, flujos simplificados y datos útiles para la toma de decisiones.",
    timeline: [
      { year: "2019–2021", event: "Registro de trauma basado en REDCap implementado en Hospital Roosevelt." },
      { year: "2021", event: "Registro descontinuado." },
      { year: "2024–2025", event: "Evaluación del registro y consulta con personal clínico y actores clave." },
      { year: "2025–2026", event: "Desarrollo de la plataforma OpenTrauma Registry." },
      { year: "2026", event: "Lista para demostración y solicitudes de implementación." },
    ],
  },
  evidence: {
    tag: "Evidencia",
    title: "Evaluación y rediseño del registro de trauma.",
    subtitle: "El rediseño se basó en la evaluación del registro descontinuado y en la retroalimentación del personal clínico y registradores.",
    abstract_title: "Cuando los registros de trauma fallan: rediseño de bajo costo a partir de la experiencia en Guatemala",
    event: "38° Congreso Panamericano de Trauma · PTS 2026 · Cartagena, Colombia",
    findings: [
      "775 pacientes registrados antes del cierre del registro",
      "Barreras principales: conectividad, tiempo de captura, complejidad de la interfaz, incompatibilidad con dispositivos móviles y carga de trabajo del registrador",
      "Las variables con mayor valor clínico tuvieron menor completitud",
      "La plataforma rediseñada incorpora funcionamiento sin internet, uso bilingüe, scores automáticos, paneles de calidad y exportación de datos",
    ],
    cta: "Leer resumen",
  },
  team: {
    tag: "Equipo",
    title: "Equipo del proyecto y socios de implementación.",
    subtitle: "Colaboradores en cirugía de trauma, cirugía global, medicina de urgencias, ciencia de implementación y sistemas de datos clínicos.",
    research_title: "Equipo de investigación",
    advisors_title: "Asesores académicos",
    guatemala_title: "Equipo de implementación en Guatemala",
  },
  partners: {
    tag: "Socios",
    title: "Socios y centros de implementación.",
    subtitle: "Instituciones clínicas, académicas y de salud pública que colaboran en la atención del trauma y la implementación del registro.",
    future: "¿Tu institución quiere sumarse como socio de implementación?",
    future_cta: "Contáctanos",
  },
  implementation: {
    tag: "Apoyo en implementación",
    title: "Cómo podemos trabajar con tu hospital.",
    body: "Nuestro equipo puede apoyar a tu hospital en la revisión de objetivos, configuración de la plataforma, adaptación de variables, creación de usuarios, capacitación de registradores y planificación de la exportación de datos para mejora de calidad o investigación.",
    cards: [
      {
        icon: "Building2",
        title: "Configurar tu centro",
        desc: "Alta de usuarios, ajustes del centro y selección de campos del registro.",
      },
      {
        icon: "Settings2",
        title: "Adaptar el registro",
        desc: "Ajustar variables y opciones locales a las necesidades de tu hospital.",
      },
      {
        icon: "Users",
        title: "Capacitar al equipo",
        desc: "Acompañamiento en la incorporación de registradores y revisión del flujo de captura.",
      },
      {
        icon: "BarChart2",
        title: "Usar los datos",
        desc: "Paneles de control y exportaciones para informes, mejora de calidad e investigación.",
      },
    ],
    cta: "Solicitar piloto",
  },
  demo: {
    tag: "Demo",
    title: "Acceso a la demo.",
    subtitle: "Explora el flujo del registro, los paneles de control, los scores y las funciones de exportación con datos de ejemplo. No se incluyen datos reales de pacientes.",
    note: "Los casos de trauma de ejemplo están precargados para explorar los paneles de control y la exportación de datos.",
    cards: [
      {
        flag: "🇬🇹",
        label: "Demo · Centro Guatemala",
        recommended: false,
        email: "test@respond.gt",
        pass: "testpassword123",
        note: "Datos de prueba precargados para el entorno de implementación de Guatemala.",
      },
      {
        flag: "🌎",
        label: "Demo · Centro Internacional",
        recommended: true,
        email: "demo@respondtraumaregistry.com",
        pass: "RESPOND2026!",
        note: "Casos de ejemplo para explorar los paneles de control y la exportación de datos.",
      },
    ],
    email_label: "Correo electrónico",
    pass_label: "Contraseña",
    login_cta: "Probar la demo",
  },
  contact: {
    tag: "Solicitar implementación",
    title: "Solicitar un piloto.",
    subtitle:
      "Cuéntanos sobre tu hospital o programa de trauma. Podemos dar seguimiento sobre acceso a la demo, configuración de la plataforma, adaptación de variables, capacitación de registradores o colaboración multicéntrica.",
    fields: {
      name: "Nombre",
      email: "Correo electrónico",
      institution: "Institución u hospital",
      country: "País",
      role: "Rol",
      center_type: "Tipo de centro",
      volume: "Volumen mensual estimado de trauma",
      interest: "Interés principal",
      message: "Mensaje",
    },
    roles: ["Cirujano/a de trauma", "Médico/a de urgencias", "Enfermería", "Investigador/a", "Registrador/a o gestor/a de datos", "Administrador/a hospitalario/a", "Otro"],
    center_types: ["Hospital público", "Hospital privado", "Centro médico académico", "Hospital comunitario", "Entorno de conflicto o emergencia humanitaria", "Institución de investigación", "Otro"],
    interests: [
      "Probar la demo",
      "Solicitar piloto",
      "Implementación en un centro",
      "Colaboración multicéntrica",
      "Alianza de investigación",
      "Preguntas técnicas",
    ],
    submit: "Enviar solicitud",
    success_title: "Solicitud recibida.",
    success_body: "Nos pondremos en contacto en 2–3 días hábiles.",
  },
  footer: {
    description:
      "OpenTrauma Registry es una plataforma gratuita y de código abierto para la captura estandarizada de datos de trauma, mejora de calidad e investigación. Primera implementación: Hospital Roosevelt, Guatemala.",
    links: [
      { label: "Por qué importa", href: "#about" },
      { label: "Plataforma", href: "#platform" },
      { label: "Evidencia", href: "#evidence" },
      { label: "Demo", href: "#demo" },
      { label: "Solicitar implementación", href: "#contact" },
      { label: "GitHub", href: "https://github.com" },
      { label: "Contacto", href: "#contact" },
    ],
    copyright: "Open Trauma Registry · Código abierto · Gratuito para centros de trauma",
  },
};

export const CONTENT: Record<Locale, typeof en> = { en, es };
export type LandingCopy = typeof en;
